### ISSUE TITLE
make sure to comment main parts of code

### ISSUE THREAD

**Issue by ad3429** [PerKaae/TeaCozy#1]
https://github.com/PerKaae/TeaCozy/blob/master/index.html#L1-L96

Make sure to comment the main parts of your HTML further in future projects. I noticed you had a few, but you can extend this further. Commenting becomes increasingly important as your projects become larger and more complex. Here is a quick refresher on commenting in HTML:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/33889591-92f4b338-df1e-11e7-8472-4d39c50e30c8.png">

**Comment by PerKaae** [comment]
Understood
